default_language_version:
    python: python3.11
repos:
    - hooks:
        - id: check-json
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: pretty-format-json
          args:
            - --autofix
        - id: detect-private-key
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
    - hooks:
        - id: forbid-tabs
          exclude: binary|\.bin$
          exclude_types:
            - python
            - javascript
            - dtd
            - markdown
            - makefile
            - xml
      repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.4
    - hooks:
        - id: shell-lint
          exclude: template|\.template$
      repo: https://github.com/jameswoolfenden/pre-commit-shell
      rev: 0.0.2
    - hooks:
        - id: markdownlint
      repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.37.0
    - hooks:
        - id: terraform-fmt
          language_version: python3.11
        - id: tf2docs
          language_version: python3.11
      repo: https://github.com/jameswoolfenden/pre-commit
      rev: v0.1.50
    - hooks:
        - id: checkov
          entry: checkov -d example/examplea --external-checks-dir checkov --download-external-modules true --compact
          files: .
          verbose: true
      repo: https://github.com/bridgecrewio/checkov
      rev: 3.0.16
    - hooks:
        - id: pike-docs-go
          args:
            - readme
            - -d
            - .
            - -i
      repo: https://github.com/jameswoolfenden/pike
      rev: v0.2.109
    - hooks:
        - id: ghat-go
          name: swot
          args:
            - swot
            - -d
            - .
        - id: ghat-go
          name: sift
          always_run: true
          args:
            - sift
            - -d
            - .
      repo: https://github.com/jameswoolfenden/ghat
      rev: v0.1.1
