---
# yamllint disable rule:line-length
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: read-all

env:
  tf_target_dir: example/examplea
  branch: main
  GITHUB_API_TOKEN: ${{ github.token }}
jobs:
  tofu:
    runs-on: ubuntu-latest
    steps:
      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Config OpenTofu plugin cache
        run: |
          echo "plugin_cache_dir = \"$HOME/.tofu.d/plugin-cache\"" >~/.tofurc
          mkdir --parents ~/.tofu.d/plugin-cache
      - name: Cache OpenTofu
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.tofu.d/plugin-cache
          key: ${{ runner.os }}-tofu-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tofu-
      - name: OpenTofu Init
        id: init
        run: tofu init
        working-directory: ${{ env.tf_target_dir }}
      - name: OpenTofu validate
        id: validate
        run: tofu validate
        working-directory: ${{ env.tf_target_dir }}
      - name: OpenTofu plan
        id: plan
        run: tofu plan
        working-directory: ${{ env.tf_target_dir }}
        env:
          GOOGLE_CLOUD_KEYFILE_JSON: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.11
      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
      - run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          mkdir "$GITHUB_WORKSPACE/bin"
          tar -xvf terraform-docs*.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/terraform-docs"
          wget https://github.com/rhysd/actionlint/releases/download/v1.6.23/actionlint_1.6.23_linux_amd64.tar.gz
          tar -xvf actionlint_1.6.23_linux_amd64.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/actionlint"
          echo "$GITHUB_WORKSPACE/bin" >> "$GITHUB_PATH"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  version:
    permissions:
      contents: write
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: [tofu, security]
